### ISSUE TITLE
http://webgoatphp.com/ is down

### ISSUE THREAD

**Issue by nhajiyani** [shivamdixit/WebGoatPHP#47]
Hi,
This is not an issue per se with your repo, I am wondering whats happening with the webgoat project now that it is down.

Thanks.

**Comment by abiusx** [comment]
Hmm…
I hosted the website personally. Now that I’m no longer partaking in OWASP, we need volunteers to do that.
-A

**Comment by shivamdixit** [comment]
Hi @nhajiyani,

We will be bringing the website back up soon. You need to host the application locally till then. 

Thanks!
