### ISSUE TITLE
unable to setup properly

### ISSUE THREAD

**Issue by misfir3** [shivamdixit/WebGoatPHP#48]
if email is better for this, let me know. I saw WebGoat PHP demo'd briefly at the AppSec USA project summit.  I am attempting to run it on a LAMP stack (apache 2.4.18, mysql 5.7.16 & php  7.0.8), but am getting nowhere. One persistent error in the log is:
`Uncaught Error: Class 'jf' not found in /var/www/html/webgoat-php/app/view/default/about.php:3\nStack trace:\n#0 {main}\n  thrown in /var/www/html/webgoat-php/app/view/default/about.php on line 3, referer: http://localhost/webgoat-php/app/view/default/
`
The db is created and all wired up ... not getting any errors that way. Any ideas/help?

**Comment by abiusx** [comment]
Is the .htaccess there and enabled?

**Comment by misfir3** [comment]
.htaccess file is there and mod_rewrite appears enabled as well as the following in apache2.conf 
`AccessFileName .htaccess`

Admittedly, my apache-fu has slipped some here, but .htaccess is usually on by default, no?

**Comment by abiusx** [comment]
Not if you don't enable AllowOverride, especially in Ubuntu. 
Change allowOverride to All on Apache config for your web root.
-A

**Comment by misfir3** [comment]
Yeah, just started looking at that and it started to come back to me ... Changed that, but still no joy :-/

**Comment by abiusx** [comment]
I don't remember all the details, so you gotta give me some more information!
What did you do and where are you at?

Which URL are you trying to access?
-A

**Comment by misfir3** [comment]
Going to reinstall and come at it fresh later. Too many other threads today. Thx for the prompt replies.

**Comment by misfir3** [comment]
had to do 
`AllowOverride All`
in apache2.conf
as well as 
`$ sudo a2enmod rewrite`
... even though I thought rewrite as already enabled. Maybe I'm just too far removed from my apache config, but might be something good to add to your docs.

Cheers!
